version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: "copy-paste-link-be-local_app"
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  redis_data:
